# Minimal robot_mcp configuration example
# This will be populated in Phase 2 (Configuration System)

mcp_http_server:
  ros__parameters:
    server:
      host: "0.0.0.0"
      port: 8080

    # Example actions, services, and topics will be added later
